### ISSUE TITLE
Only first letter is rendered

### ISSUE THREAD

**Issue by Poggen** [remotion-dev/template-skia#4]
I just tried this template out, but it seems like only the first path is being rendered, even though the `progress` interpolation seems to be working when I log `paths`:

![image](https://user-images.githubusercontent.com/5216834/192567863-865f76d3-555f-4c1f-8d2d-464b1397c9fe.png)
![image](https://user-images.githubusercontent.com/5216834/192567964-145ccf52-e63e-44d1-973a-af8aab6906be.png)

**Comment by JonnyBurger** [comment]
Hi @Poggen! This seems to have broken in React Native Skia v0.1.146 - I have filed an issue in their repo: https://github.com/Shopify/react-native-skia/issues/967 and have for now pinned the template to use an older version.

Will coordinate to get everything aligned again!

**Comment by JonnyBurger** [comment]
Fixed now!
