### ISSUE TITLE
Render HelloSkia throws `errorMessage` undefined error

### ISSUE THREAD

**Issue by dafinley** [remotion-dev/template-skia#5]
When I try to render the HelloSkia composition the command fails with a `errorMessage` is undefined

<img width="616" alt="Screen Shot 2023-02-09 at 11 18 56 AM" src="https://user-images.githubusercontent.com/441184/217872188-53b45c09-ef6e-45b1-853c-b10861212374.png">

**Comment by JonnyBurger** [comment]
Hi @dafinley! 

Very sorry I missed the issue.
This error message should be fixed in the meanwhile if you run `npx remotion upgrade`, in one of the recent releases, we fixed this.
