### ISSUE TITLE
Template - upgrade, Skia

### ISSUE THREAD

**Issue by MehmetAdemi** [remotion-dev/template-skia#6]

**Comment by JonnyBurger** [comment]
This one is complicated, we also remove some dependencies and upgrade Skia at the same time. I'm gonna take care of that part...

**Comment by MehmetAdemi** [comment]
Thanks!

**Comment by JonnyBurger** [comment]
Ok, I did what I had to do 🫡 You can do the normal procedure @MehmetAdemi
